name: CI

on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # Required due to: https://github.com/python/mypy/issues/7771
      FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: pip install --disable-pip-version-check --progress-bar off --editable .[development]
      - name: Run flake8
        run: flake8 --show-source --color always
      - name: Run pylint
        run: pylint salesforce_functions/ tests/
      - name: Run mypy
        run: mypy
      - name: Run Black
        run: black --check --diff --color .
      - name: Run isort
        run: isort --check-only --diff --color .

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: pip install --disable-pip-version-check --progress-bar off --editable .[development]
      - name: Set up Java 11 for WireMock (non-Windows only)
        if: runner.os != 'Windows'
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Download WireMock (non-Windows only)
        if: runner.os != 'Windows'
        run: curl --fail --retry 3 --retry-connrefused --connect-timeout 5 --max-time 60 -o wiremock.jar https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/2.35.0/wiremock-jre8-standalone-2.35.0.jar
      - name: Start WireMock (non-Windows only)
        if: runner.os != 'Windows'
        run: java -jar wiremock.jar --root-dir tests/wiremock --port 12345 &
      - name: Run pytest (tests that work on all platforms)
        run: pytest --verbosity 2 --color yes
      - name: Run pytest (tests that require WireMock)
        if: runner.os != 'Windows'
        run: pytest --verbosity 2 --color yes -m requires_wiremock --cov-append
      - name: Check code coverage (non-Windows only)
        if: runner.os != 'Windows'
        run: coverage report --show-missing --fail-under=100
